# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21.5
	yarn_mappings=1.21.5+build.1
	loader_version=0.16.13

# Mod Properties
	mod_version = 4.1.2+1.21.5
	maven_group = com.minenash
	archives_base_name = custom_hud

# Dependencies
	#Fabric api
	fabric_version=0.119.9+1.21.5
	modmenu_version=14.0.0-rc.2
