package com.minenash.customhud.errors;

public enum ErrorType {
    IO, UNKNOWN_VARIABLE, UNKNOWN_VARIABLE_FLAG, MALFORMED_CONDITIONAL,
    INVALID_TIME_FORMAT, UNKNOWN_STATISTIC, UNKNOWN_ITEM_ID,
    UNKNOWN_SLOT, UNAVAILABLE_SLOT, UNKNOWN_ITEM_PROPERTY,
    UNKNOWN_SETTING, UNKNOWN_KEYBOARD_KEY, UNKNOWN_SOUND_CATEGORY,

    CONDITIONAL_UNEXPECTED_VALUE, CONDITIONAL_WRONG_NUMBER_OF_TOKENS
}
