package com.minenash.customhud.elements.supplier;

import com.minenash.customhud.core.data.Enabled;

import static com.minenash.customhud.core.data.Enabled.*;
import static com.minenash.customhud.elements.supplier.BooleanSuppliers.*;
import static com.minenash.customhud.elements.supplier.DecimalSuppliers.*;
import static com.minenash.customhud.elements.supplier.IntegerSuppliers.*;
import static com.minenash.customhud.elements.supplier.SpecialSuppliers.*;
import static com.minenash.customhud.elements.supplier.StringIntSuppliers.*;
import static com.minenash.customhud.elements.supplier.StringSuppliers.*;
import static com.minenash.customhud.core.SupplierRegistry.add;
import static com.minenash.customhud.core.SEntry.Type.*;

public class RegisterSuppliers {

    static {
        add(NONE, BOOLEAN, VSYNC, "vsync");
        add(NONE, BOOLEAN, SINGLEPLAYER, "sp", "singleplayer");
        add(NONE, BOOLEAN, MULTIPLAYER, "mp", "multiplayer");
        add(NONE, BOOLEAN, CHUNK_CULLING, "chunks_culling");
        add(NONE, BOOLEAN, IN_OVERWORLD, "overworld");
        add(NONE, BOOLEAN, IN_NETHER, "nether");
        add(NONE, BOOLEAN, IN_END, "end");
        add(WORLD, BOOLEAN, IS_RAINING, "raining");
        add(WORLD, BOOLEAN, IS_THUNDERING, "thundering");
        add(WORLD, BOOLEAN, IS_SNOWING, "snowing");
        add(WORLD, BOOLEAN, IS_SLIME_CHUNK, "slime_chunk");
        add(NONE, BOOLEAN, SPRINTING, "sprinting");
        add(NONE, BOOLEAN, SNEAKING, "sneaking");
        add(NONE, BOOLEAN, SWIMMING, "swimming");
        add(NONE, BOOLEAN, ON_GROUND, "on_ground");
        add(NONE, BOOLEAN, ITEM_HAS_DURABILITY, "item_has_durability", "item_has_dur");
        add(NONE, BOOLEAN, OFFHAND_ITEM_HAS_DURABILITY, "offhand_item_has_durability", "oitem_has_dur");
        add(NONE, BOOLEAN, FISHING_IS_CAST, "fishing_is_cast");
        add(NONE, BOOLEAN, FISHING_IS_HOOKED, "fishing_is_hooked");
        add(NONE, BOOLEAN, FISHING_HAS_CAUGHT, "fishing_has_caught");
        add(NONE, BOOLEAN, FISHING_IN_OPEN_WATER, "fishing_in_open_water");

        add(NONE, STRING, VERSION, "version");
        add(NONE, STRING, CLIENT_VERSION, "client_version");
        add(NONE, STRING, MODDED_NAME, "modded_name");
        add(NONE, STRING, DISPLAY_NAME, "display_name", "name");
        add(NONE, STRING, USERNAME, "username");
        add(NONE, STRING, UUID, "uuid");
        add(NONE, STRING, DIMENSION, "dimension");
        add(NONE, STRING, DIMENSION_ID, "dimension_id");
        add(NONE, STRING, FACING, "facing");
        add(NONE, STRING, FACING_SHORT, "facing_short");
        add(NONE, STRING, FACING_TOWARDS_XZ, "facing_towards_xz");
        add(NONE, STRING, BIOME, "biome");
        add(NONE, STRING, BIOME_ID, "biome_id");
        add(CLIENT_CHUNK, STRING, MOON_PHASE_WORD, "moon_phase_word");
        add(NONE, STRING, TARGET_ENTITY, "target_entity", "te");
        add(NONE, STRING, TARGET_ENTITY_ID, "target_entity_id", "tei");
        add(NONE, STRING, TARGET_ENTITY_NAME, "target_entity_name", "ten");
        add(NONE, STRING, TARGET_ENTITY_UUID, "target_entity_uuid", "teu");
        add(NONE, STRING, HOOKED_ENTITY, "hooked_entity", "he");
        add(NONE, STRING, HOOKED_ENTITY_ID, "hooked_entity_id", "hei");
        add(NONE, STRING, HOOKED_ENTITY_NAME, "hooked_entity_name", "hen");
        add(NONE, STRING, HOOKED_ENTITY_UUID, "hooked_entity_uuid", "heu");
        add(NONE, STRING, WORLD_NAME, "world_name", "world");
        add(NONE, STRING, SERVER_NAME, "server_name");
        add(NONE, STRING, SERVER_ADDRESS, "server_address", "address", "ip");
        add(NONE, STRING, SERVER_BRAND, "server_brand");
        add(NONE, STRING, JAVA_VERSION, "java_version");
        add(NONE, STRING, CPU_NAME, "cpu_name");
        add(NONE, STRING, GPU_NAME, "gpu_name");
        add(TIME, STRING, TIME_AM_PM, "am_pm");

        add(NONE, STR_INT, PARTICLES, "particles", "p");
        add(SOUND, STR_INT, STREAMING_SOUNDS, "streaming_sounds", "sounds");
        add(SOUND, STR_INT, MAX_STREAMING_SOUNDS, "max_streaming_sounds", "max_sounds");
        add(SOUND, STR_INT, STATIC_SOUNDS, "static_sounds");
        add(SOUND, STR_INT, MAX_STATIC_SOUNDS, "max_static_sounds");

        add(NONE, INT, FPS, "fps");
        add(NONE, INT, MAX_FPS, "max_fps");
        add(NONE, INT, BIOME_BLEND, "biome_blend");
        add(NONE, INT, SIMULATION_DISTANCE, "simulation_distance", "sd");
        add(NONE, INT, PACKETS_SENT, "packets_sent", "tx");
        add(NONE, INT, PACKETS_RECEIVED, "packets_received", "rx");
        add(NONE, INT, CHUNKS_RENDERED, "chunks_rendered");
        add(NONE, INT, CHUNKS_LOADED, "chunks_loaded");
        add(NONE, INT, RENDER_DISTANCE, "render_distance");
        add(NONE, INT, QUEUED_TASKS, "queued_tasks");
        add(NONE, INT, UPLOAD_QUEUE, "upload_queue");
        add(NONE, INT, BUFFER_COUNT, "buffer_count");
        add(NONE, INT, ENTITIES_RENDERED, "entities_rendered");
        add(NONE, INT, ENTITIES_LOADED, "entities_loaded");
        add(WORLD, INT, FORCED_LOADED_CHUNKS, "force_loaded_chunks", "fc");
        add(NONE, INT, BLOCK_X, "block_x", "bx");
        add(NONE, INT, BLOCK_Y, "block_y", "by");
        add(NONE, INT, BLOCK_Z, "block_z", "bz");
        add(WORLD | Enabled.TARGET_BLOCK, INT, TARGET_BLOCK_X, "target_block_x", "target_x", "tbx");
        add(WORLD | Enabled.TARGET_BLOCK, INT, TARGET_BLOCK_Y, "target_block_y", "target_y", "tby");
        add(WORLD | Enabled.TARGET_BLOCK, INT, TARGET_BLOCK_Z, "target_block_z", "target_z", "tbz");
        add(WORLD | Enabled.TARGET_BLOCK, INT, TARGET_BLOCK_DISTANCE, "target_block_distance", "target_distance", "tbd");
        add(WORLD | Enabled.TARGET_FLUID, INT, TARGET_FLUID_X, "target_fluid_x", "tfx");
        add(WORLD | Enabled.TARGET_FLUID, INT, TARGET_FLUID_Y, "target_fluid_y", "tfy");
        add(WORLD | Enabled.TARGET_FLUID, INT, TARGET_FLUID_Z, "target_fluid_z", "tfz");
        add(WORLD | Enabled.TARGET_FLUID, INT, TARGET_FLUID_DISTANCE, "target_fluid_distance", "tfd");
        add(NONE, INT, IN_CHUNK_X, "in_chunk_x", "icx");
        add(NONE, INT, IN_CHUNK_Y, "in_chunk_y", "icy");
        add(NONE, INT, IN_CHUNK_Z, "in_chunk_z", "icz");
        add(NONE, INT, CHUNK_X, "chunk_x", "cx");
        add(NONE, INT, CHUNK_Y, "chunk_y", "cy");
        add(NONE, INT, CHUNK_Z, "chunk_z", "cz");
        add(NONE, INT, REGION_X, "region_x", "rex");
        add(NONE, INT, REGION_Z, "region_z", "rez");
        add(NONE, INT, REGION_RELATIVE_X, "region_relative_x", "rrx");
        add(NONE, INT, REGION_Z, "region_relative_z", "rrz");
        add(CLIENT_CHUNK, INT, CLIENT_LIGHT, "client_light", "light");
        add(CLIENT_CHUNK, INT, CLIENT_LIGHT_SKY, "client_light_sky", "light_sky");
        add(CLIENT_CHUNK, INT, CLIENT_LIGHT_SUN, "client_light_sun", "light_sun");
        add(CLIENT_CHUNK, INT, CLIENT_LIGHT_BLOCK, "client_light_block", "light_block");
        add(WORLD | SERVER_CHUNK, INT, SERVER_LIGHT_SKY, "server_light_sky");
        add(WORLD | SERVER_CHUNK, INT, SERVER_LIGHT_BLOCK, "server_light_block");
        add(CLIENT_CHUNK, INT, CLIENT_HEIGHT_MAP_SURFACE, "client_height_map_surface", "chs");
        add(CLIENT_CHUNK, INT, CLIENT_HEIGHT_MAP_MOTION_BLOCKING, "client_height_map_motion_blocking", "chm");
        add(SERVER_CHUNK, INT, SERVER_HEIGHT_MAP_SURFACE, "server_height_map_surface", "shs");
        add(SERVER_CHUNK, INT, SERVER_HEIGHT_MAP_OCEAN_FLOOR, "server_height_map_ocean_floor", "sho");
        add(SERVER_CHUNK, INT, SERVER_HEIGHT_MAP_MOTION_BLOCKING, "server_height_map_motion_blocking", "shm");
        add(SERVER_CHUNK, INT, SERVER_HEIGHT_MAP_MOTION_BLOCKING_NO_LEAVES, "server_height_map_motion_blocking_no_leaves", "shml");
        add(CLIENT_CHUNK, INT, MOON_PHASE, "moon_phase");
        add(SERVER_WORLD, INT, SPAWN_CHUNKS, "spawn_chunks", "sc");
        add(SERVER_WORLD, INT, MONSTERS, "monsters");
        add(SERVER_WORLD, INT, CREATURES, "creatures");
        add(SERVER_WORLD, INT, AMBIENT_MOBS, "ambient_mobs");
        add(SERVER_WORLD, INT, WATER_CREATURES, "water_creatures");
        add(SERVER_WORLD, INT, WATER_AMBIENT_MOBS, "water_ambient_mobs");
        add(SERVER_WORLD, INT, UNDERGROUND_WATER_CREATURE, "underground_water_creatures");
        add(SERVER_WORLD, INT, AXOLOTLS, "axolotls");
        add(SERVER_WORLD, INT, MISC_MOBS, "misc_mobs");
        add(NONE, INT, JAVA_BIT, "java_bit");
        add(NONE, INT, CPU_CORES, "cpu_cores");
        add(NONE, INT, CPU_THREADS, "cpu_threads");
        add(NONE, INT, DISPLAY_WIDTH, "display_width");
        add(NONE, INT, DISPLAY_HEIGHT, "display_height");
        add(NONE, INT, DISPLAY_REFRESH_RATE, "display_refresh_rate");
        add(NONE, INT, MODS, "mods");
        add(NONE, INT, PING, "ping");
        add(NONE, INT, SOLAR_TIME, "time", "solar_time");
        add(NONE, INT, LUNAR_TIME, "lunar_time");
        add(NONE, INT, ITEM_DURABILITY, "item_durability", "item_dur");
        add(NONE, INT, ITEM_MAX_DURABILITY, "item_max_durability", "item_max_dur");
        add(NONE, INT, OFFHAND_ITEM_DURABILITY, "offhand_item_durability", "oitem_dur");
        add(NONE, INT, OFFHAND_ITEM_MAX_DURABILITY, "offhand_item_max_durability", "oitem_max_dur");
        add(TIME, INT, TIME_HOUR_12, "hour12", "hour");
        add(CLICKS_PER_SECONDS, INT, LCPS, "left_clicks_per_second", "lcps");
        add(CLICKS_PER_SECONDS, INT, RCPS, "right_clicks_per_second", "rcps");

        add(NONE, DEC, X, "x");
        add(NONE, DEC, Y, "y");
        add(NONE, DEC, Z, "z");
        add(NONE, DEC, X, "nether_x", "nx");
        add(NONE, DEC, X, "nether_z", "nz");
        add(NONE, DEC, X, "target_entity_x", "tex");
        add(NONE, DEC, X, "target_entity_y", "tey");
        add(NONE, DEC, X, "target_entity_z", "tez");
        add(NONE, DEC, X, "target_entity_distance", "ted");
        add(NONE, DEC, X, "hooked_entity_x", "hex");
        add(NONE, DEC, X, "hooked_entity_y", "hey");
        add(NONE, DEC, X, "hooked_entity_z", "hez");
        add(NONE, DEC, X, "hooked_entity_distance", "hed");
        add(NONE, DEC, X, "reach_distance", "reach");
        add(NONE, DEC, X, "fishing_hook_distance");
        add(NONE, DEC, X, "velocity_xz");
        add(NONE, DEC, X, "velocity_y");
        add(NONE, DEC, X, "velocity_xyz");
        add(NONE, DEC, X, "velocity_xz_kmh");
        add(NONE, DEC, X, "velocity_y_kmh");
        add(NONE, DEC, X, "velocity_xyz_kmh");
        add(NONE, DEC, X, "yaw");
        add(NONE, DEC, X, "pitch");
        add(NONE, DEC, X, "day");
        add(NONE, DEC, X, "mood");
        add(NONE, DEC, X, "tps");
        add(NONE, DEC, X, "memory_used_percentage");
        add(NONE, DEC, X, "memory_used");
        add(NONE, DEC, X, "memory_total");
        add(NONE, DEC, X, "memory_allocated_percentage");
        add(NONE, DEC, X, "memory_allocated");
        add(NONE, DEC, X, "cpu_usage", "cpu");
        add(NONE, DEC, X, "gpu_usage", "gpu");
        add(NONE, DEC, X, "ms_ticks", "tick_ms");
        add(NONE, DEC, X, "frame_ms_min");
        add(NONE, DEC, X, "frame_ms_max");
        add(NONE, DEC, X, "frame_ms_avg");
        add(NONE, DEC, X, "frame_ms_samples");
        add(NONE, DEC, X, "item_durability_percent", "item_dur_per");
        add(NONE, DEC, X, "offhand_item_durability_percent", "oitem_dur_per");
        add(NONE, DEC, X, "local_difficulty");
        add(NONE, DEC, X, "clamped_local_difficulty");

        add(TIME, SPECIAL, TIME_HOUR_24, "hour24");
        add(TIME, SPECIAL, TIME_MINUTES, "minute");
        add(TIME, SPECIAL, TIME_SECONDS, "second");
        add(WORLD | Enabled.TARGET_BLOCK, SPECIAL, SpecialSuppliers.TARGET_BLOCK, "target_block", "tb");
        add(WORLD | Enabled.TARGET_BLOCK, SPECIAL, TARGET_BLOCK_ID, "target_block_id", "tbi");
        add(WORLD | Enabled.TARGET_FLUID, SPECIAL, SpecialSuppliers.TARGET_FLUID, "target_fluid", "tf");
        add(WORLD | Enabled.TARGET_FLUID, SPECIAL, TARGET_FLUID_ID, "target_fluid_id", "tfi");
        add(NONE, SPECIAL, ITEM, "item");
        add(NONE, SPECIAL, ITEM_NAME, "item_name");
        add(NONE, SPECIAL, ITEM_ID, "item_id");
        add(NONE, SPECIAL, OFFHAND_ITEM, "offhand_item", "oitem");
        add(NONE, SPECIAL, OFFHAND_ITEM_NAME, "offhand_item_name");
        add(NONE, SPECIAL, OFFHAND_ITEM_ID, "offhand_item_id", "oitem_id");
        add(NONE, SPECIAL, CLOUDS, "clouds");
        add(NONE, SPECIAL, GRAPHICS_MODE, "graphics_mode");
        add(NONE, SPECIAL, FACING_TOWARDS_PN_WORD, "facing_towards_pn_word");
        add(NONE, SPECIAL, FACING_TOWARDS_PN_SIGN, "facing_towards_pn_sign");

    }

}
